server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8001
    #context-path: /huashi-document-sign-server
# DataSource
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db.hspaas.cn:3306/dbs?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: hspaas
      password: Hangzhou_Huashi_0088664422@
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot huashi-document-sign-server
  application:
    name: huashi-document-sign-server
  cloud:
    consul:
      #host: localhost
      #port: 8500
      config:
        enabled: false #false禁用Consul配置，默认true
      #discovery:
       # serviceName: ${spring.application.name}	# 注册到consul的服务名称
  boot:
# 开放健康检查接口
#management:
 # endpoints:
  #  web:
 #     exposure:
  #      include: "*"
 # endpoint:
  #  health:
  #    show-details: ALWAYS
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

storage:
  model:
    home: /Users/tenx/Documents/test/model/xml/
    target: /Users/tenx/Documents/test/model/xml/target/
    download: /Users/tenx/Documents/test/model/xml/download/
    print: /Users/tenx/Documents/test/model/xml/print/
    domain: http://localhost:8999/pdf/
  resource:
    path: /Users/tenx/Documents/test/pic/
    domain: http://localhost/resource/